import React from "react";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "../lib/AntdRegistry";
import "./globals.css";

// === COMPONENT === ///
import Header from "./layout/Header";
import SideBar from "./layout/SideBar";
import Footer from "./layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Full-stack-developer-assignment",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <StyledComponentsRegistry>
//           <Header />
//           <div className="layout-wrapper">
//             <SideBar />
//             <div className="content-wrapper">{children}</div>
//           </div>
//         </StyledComponentsRegistry>
//       </body>
//     </html>
//   );
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
